### ISSUE TITLE
Error on building while using node8.17.0

### ISSUE THREAD

**Issue by lchimaru** [privatenumber/esbuild-loader#108]
## Bug description
Build fails on node version 8.17.0 with following info:
```
 TypeError: Invalid data, chunk must be a string or buffer, not object
✖ ERROR TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:708:11)
    at Object.writeToStdin (/home/user/project/node_modules/esbuild/lib/main.js:1376:19)
    at sendResponse (/home/user/project/node_modules/esbuild/lib/main.js:566:14)
    at /home/user/project/node_modules/esbuild/lib/main.js:620:7
    at Generator.next (<anonymous>)
    at Promise (/home/user/project/node_modules/esbuild/lib/main.js:27:61)
    at new Promise (<anonymous>)
    at __async (/home/user/project/node_modules/esbuild/lib/main.js:9:10)
    at handleRequest (/home/user/project/node_modules/esbuild/lib/main.js:568:40)
    at handleIncomingPacket (/home/user/project/node_modules/esbuild/lib/main.js:635:7)
    at Socket.readFromStdout (/home/user/project/node_modules/esbuild/lib/main.js:520:7)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
````

I was trying to use newest alpha version of esbuild-loader (`3.0.0-alpha.1`) and older ones (`1.3.1`) but with no success. Upgrading node to 10.23.3 is solving this issue, but it would be good to have older nodes support.

## Reproduction steps
1. use node version 8.17.0 and npm 6.13.4
2. install dependencies
3. try to build using esbuild-loader

## Environment

- `esbuild-loader` version: 2.9.1
- Operating System: Ubuntu20.10
- Node version: 8.17.0
- Package manager (npm/yarn/pnpm) and version: 6.13.4

**Comment by privatenumber** [comment]
Based on your error stack, it seems that the incompatibility is coming from esbuild rather than esbuild-loader.

Node.js 8 LTS has ended but you can give try requesting support at https://github.com/evanw/esbuild
