### ISSUE TITLE
fails when used together with individual packaging in serverless

### ISSUE THREAD

**Issue by kabo** [privatenumber/esbuild-loader#6]
Hi,

I'm using [serverless](https://github.com/serverless/serverless) with [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack).

When using `esbuild-loader` it works fine if my `serverless.yml` has

```yml
package:
  individually: false
```

But if I have

```yml
package:
  individually: true
```

it spits out a bunch of errors when I try to build. A small sample:

```
ERROR in ./node_modules/ldapts/messages/AbandonRequest.js
Module build failed (from ./node_modules/esbuild-loader/src/index.js):
Error: [esbuild-loader] You need to add ESBuildPlugin to your webpack config first
    at Object.module.exports (/dir/node_modules/esbuild-loader/src/index.js:15:7)
 @ ./node_modules/ldapts/messages/index.js 24:13-40
 @ ./node_modules/ldapts/Client.js
 @ ./node_modules/ldapts/index.js
 @ ./src/helpers/getLdapClient.ts
 @ ./src/handlers/addUser.ts

ERROR in ./node_modules/ldapts/messages/AddRequest.js
Module build failed (from ./node_modules/esbuild-loader/src/index.js):
Error: [esbuild-loader] You need to add ESBuildPlugin to your webpack config first
    at Object.module.exports (/dir/node_modules/esbuild-loader/src/index.js:15:7)
 @ ./node_modules/ldapts/messages/index.js 25:13-36
 @ ./node_modules/ldapts/Client.js
 @ ./node_modules/ldapts/index.js
 @ ./src/helpers/getLdapClient.ts
 @ ./src/handlers/addUser.ts
```

If I use `ts-loader` instead of `esbuild-loader` both work fine.

The `ESBuildPlugin` is obviously added to my webpack config. Not sure if this is an issue with `esbuild-loader`, `serverless-webpack`, or something else.

**Comment by bryantbiggs** [comment]
likewise, this would be great to have working in serverless applications

**Comment by privatenumber** [comment]
Im not familiar with serverless-webpack, but are you adding the ESBuildPlugin as the error says?

Do you mind sharing your webpack config?

**Comment by bryantbiggs** [comment]
hey, sure thing @privatenumber:

base:
```
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const slsw = require('serverless-webpack');
const Webpack = require('webpack');
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  // Turning off source-map in local development greatly reduces build time and memory footprint
  devtool: slsw.lib.webpack.isLocal ? false : 'cheap-module-source-map',
  resolve: {
    extensions: ['.ts', '.tsx', '.mjs', '.jsx', '.js', '.json'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    pathinfo: false,
  },
  target: 'node',
  externals: ['aws-sdk', 'utf-8-validate', 'bufferutil', 'datadog-lambda-js', 'dd-trace'],
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          // disable type checker - use the TypeFork plugin to check types
          transpileOnly: true,
        },
      },
    ],
  },
  optimization: {
    // Disable minimizer so TypeORM can work while we have better build time
    // Minification also breaks Apollo federation, for some reason
    minimize: false,
    removeAvailableModules: false,
    removeEmptyChunks: false,
    splitChunks: false,
  },
  plugins: [
    new Webpack.IgnorePlugin(/^pg-native$/),
    new FilterWarningsPlugin({
      exclude: [
        /Critical dependency: the request of a dependency is an expression/,
        /mongodb/,
        /mssql/,
        /mysql/,
        /mysql2/,
        /oracledb/,
        /pg/,
        /pg-native/,
        /pg-query-stream/,
        /redis/,
        /sqlite3/,
        /sql.js/,
        /react-native-sqlite-storage/,
      ],
    }),
  ],
};
```

extends:
```
const path = require('path');

module.exports = {
  ...require('@common-config/webpack.config'),
  output: {
    filename: '[name].js',
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    pathinfo: false,
  },
};
```

**Comment by privatenumber** [comment]
Doesn't seem like you're using `esbuild-loader` in your config.

A [minimal, repriducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem would be super helpful for me to debug if you can provide one.

**Comment by bryantbiggs** [comment]
my apologies, I copied from `master` in a haste and not my branch:

base:
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const slsw = require('serverless-webpack');
const Webpack = require('webpack');
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
const { ESBuildPlugin, ESBuildMinifyPlugin } = require('esbuild-loader');

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  // Turning off source-map in local development greatly reduces build time and memory footprint
  devtool: slsw.lib.webpack.isLocal ? false : 'cheap-module-source-map',
  resolve: {
    extensions: ['.ts', '.tsx', '.mjs', '.jsx', '.js', '.json'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    pathinfo: false,
  },
  target: 'node',
  externals: ['aws-sdk', 'utf-8-validate', 'bufferutil', 'datadog-lambda-js', 'dd-trace'],
  module: {
    rules: [
      {
        // TypeFork plugin will be used check types
        test: /\.tsx?$/,
        loader: 'esbuild-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          target: 'es2017',
        },
      },
    ],
  },
  optimization: {
    minimize: true,
    minimizer: [
      new ESBuildMinifyPlugin()
    ],
    removeAvailableModules: false,
    removeEmptyChunks: false,
    splitChunks: false,
  },
  plugins: [
    new Webpack.IgnorePlugin(/^pg-native$/),
    new FilterWarningsPlugin({
      exclude: [
        /Critical dependency: the request of a dependency is an expression/,
        /mongodb/,
        /mssql/,
        /mysql/,
        /mysql2/,
        /oracledb/,
        /pg/,
        /pg-native/,
        /pg-query-stream/,
        /redis/,
        /sqlite3/,
        /sql.js/,
        /react-native-sqlite-storage/,
      ],
    }),
    new ESBuildPlugin(),
  ],
};
```

extends-base:
```js
const path = require('path');

module.exports = {
  ...require('@common-config/webpack.config'),
  output: {
    filename: '[name].js',
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    pathinfo: false,
  },
};
```

I will put together a repro later today

**Comment by bryantbiggs** [comment]
@privatenumber here is a link to a repro with full output https://github.com/clowdhaus/dogged-params/pull/3

the code itself compiles with esbuild by running `yarn run build:esbuild`

**Comment by privatenumber** [comment]
Will look at the repro later when I have time, but at a glance, it looks like you're compiling `.tsx` files so you should specify that as the esbuild loader:

```diff
{
   test: /\.tsx?$/,
   loader: 'esbuild-loader',
   exclude: [
     [
       path.resolve(__dirname, 'node_modules'),
       path.resolve(__dirname, '.serverless'),
       path.resolve(__dirname, '.webpack'),
     ],
   ],
   options: {
+    loader: 'tsx',
     target: 'es2017',
   },
},
```

**Comment by bryantbiggs** [comment]
~thanks @privatenumber that allowed it to execute successfully but now what was a 5.3mb zip archive for my lambda has exploded to become 69.3mb zip~
nvm - had to turn back on the package individually to true

**Comment by privatenumber** [comment]
Gotcha, seems like this is resolved then
