### ISSUE TITLE
Usage in React app (Webpack 4.44.2)

### ISSUE THREAD

**Issue by leonardofaria** [privatenumber/esbuild-loader#75]
Hi

Thanks for this project.

I've trying to add the loader in a React app (not create-react-app, app with Webpack 4.44.2) however I'm getting the following error:

```
ERROR in ./app/application.js
Module build failed (from ./node_modules/esbuild-loader/dist/index.js):
Error: Transform failed with 1 error:
/path/app/application.js:24:6: error: Unexpected "<"
    at failureErrorWithLog (/path/node_modules/esbuild/lib/main.js:933:15)
    at /path/node_modules/esbuild/lib/main.js:832:33
    at handleIncomingPacket (/path/node_modules/esbuild/lib/main.js:552:9)
    at Socket.readFromStdout (/path/node_modules/esbuild/lib/main.js:468:7)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

Line 24 is using JSX:

```jsx
<Provider store={store}>
 <Component />
</Provider>,
```

Here is the webpack loader: 

```js
loader: 'esbuild-loader',
options: {
  target: 'esnext', // default, or 'es20XX', 'esnext'
  jsxFactory: 'React.createElement',
  jsxFragment: 'React.Fragment',
}
```

I am wondering if the `jsxFactory` and `jsxFragment` are not working. It looks like esbuild-loader is unable to process JSX, despite the options are there.

I looked at the package.json of this project and it looks like my webpack version is supported.

Any suggestions about what I am missing here? 

Thanks

**Comment by privatenumber** [comment]
Try adding `loader: 'jsx'` to the options

I'll update the docs "Quick Setup" section to include this example

**Comment by leonardofaria** [comment]
That worked! Thank you very much, cheers
